operatingSystem:
  windows: false

deployInfra:
  enabled: false
  storageAccount: false
  aiSearchService: false
  azureSpeechService: false
  containerRegistry: false
  appServicePremiumPlan: false
  appServiceBasicPlan: false
  eventHubService: true
  azureOpenAIService: false

envCreation:
  enabled: false

midentityCreation: 
  enabled: false

buildAndPushImagesToACR:
  enabled: false
  buildMainApp: true
  buildIngestionConsumer: true

deployAppService:
  enabled: false

deployContainerApps:
  enabled: true