operatingSystem:
  windows: false

deployInfra:
  enabled: false
  storageAccount: true
  aiSearchService: true
  azureSpeechService: true
  containerRegistry: true
  appServicePremiumPlan: true
  appServiceBasicPlan: true
  eventHubService: true
  azureOpenAIService: true

envCreation:
  enabled: false

midentityCreation: 
  enabled: false

buildAndPushImagesToACR:
  enabled: true
  buildMainApp: true
  buildIngestionConsumer: true

deployAppService:
  enabled: false

deployContainerApps:
  enabled: false