name: mmctv2
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py38h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.6.2=hbcca054_0
  - certifi=2024.6.2=py38h06a4308_0
  - cffi=1.16.0=py38h5eee18b_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cpuonly=2.0=0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.1.0=0
  - cuda-version=11.8=hcce14f8_3
  - cudatoolkit=11.8.0=h6a678d5_0
  - expat=2.6.2=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py38h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py38h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py38h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=14.1.0=h77fa898_0
  - libgomp=14.1.0=h77fa898_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.1.4=h166bdaf_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.43=h2797004_0
  - libprotobuf=4.25.3=he621ea3_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libzlib=1.2.13=h4ab18f5_6
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py38h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py38h06a4308_0
  - numpy=1.24.3=py38hf6e8229_1
  - numpy-base=1.24.3=py38h060ed82_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h9ca470c_1
  - openssl=3.3.1=h4ab18f5_1
  - pillow=10.3.0=py38h5eee18b_0
  - pip=24.0=py38h06a4308_0
  - protobuf=4.25.3=py38h12ddb61_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.19=h955ad1f_0
  - pytorch=2.3.1=py3.8_cpu_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cpu
  - pyyaml=6.0.1=py38h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.2=py38h06a4308_0
  - setuptools=69.5.1=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.12=py38h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.3.1=py38_cpu
  - torchtriton=2.3.1=py38
  - torchvision=0.18.1=py38_cpu
  - typing_extensions=4.11.0=py38h06a4308_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.43.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.5=hc292b87_2
  - pip:
      - accelerate==0.31.0
      - addict==2.4.0
      - aliyun-python-sdk-core==2.15.1
      - aliyun-python-sdk-kms==2.16.3
      - antlr4-python3-runtime==4.8
      - attrs==23.2.0
      - audioread==3.0.1
      - azure-cognitiveservices-vision-contentmoderator==1.0.0
      - azure-common==1.1.28
      - azure-core==1.30.2
      - azure-cosmos==4.7.0
      - azure-eventhub==5.12.1
      - azure-identity==1.17.1
      - azure-keyvault-secrets==4.8.0
      - azure-mgmt-compute==31.0.0
      - azure-mgmt-core==1.4.0
      - azure-mgmt-network==25.4.0
      - azure-mgmt-storage==21.2.1
      - azure-storage-blob==12.20.0
      - azure-storage-queue==12.10.0
      - bitarray==2.9.2
      - click==8.1.7
      - colorama==0.4.6
      - comm==0.2.2
      - contourpy==1.1.1
      - crcmod==1.7
      - cryptography==42.0.8
      - cycler==0.12.1
      - cython==3.0.10
      - datasets==2.18.0
      - debugpy==1.8.2
      - decord==0.6.0
      - dill==0.3.8
      - einops==0.8.0
      - et-xmlfile==1.1.0
      - fairseq==0.12.2
      - fonttools==4.53.0
      - fsspec==2024.2.0
      - ftfy==6.2.0
      - gast==0.6.0
      - hydra-core==1.0.7
      - importlib-metadata==8.0.0
      - importlib-resources==6.4.0
      - ipykernel==6.29.5
      - isodate==0.6.1
      - jmespath==0.10.0
      - jsonpointer==3.0.0
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - kiwisolver==1.4.5
      - langchain-community==0.2.6
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - llama-index==0.8.64.post1
      - llvmlite==0.41.1
      - lxml==5.2.2
      - matplotlib==3.7.5
      - modelscope==1.15.0
      - msal==1.29.0
      - msal-extensions==1.2.0
      - msgpack==1.0.8
      - msrest==0.7.1
      - multidict==6.0.5
      - multiprocess==0.70.16
      - numba==0.58.1
      - oauthlib==3.2.2
      - omegaconf==2.0.6
      - open-clip-torch==2.24.0
      - openai==1.35.10
      - opencv-python==4.10.0.84
      - openpyxl==3.1.5
      - oss2==2.18.6
      - pexpect==4.9.0
      - platformdirs==4.2.2
      - pooch==1.8.2
      - portalocker==2.10.0
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - py-cpuinfo==9.0.0
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - pycparser==2.22
      - pycryptodome==3.20.0
      - pyjwt==2.8.0
      - pyparsing==3.1.2
      - python-dotenv==1.0.1
      - pyzmq==26.0.3
      - rapidfuzz==3.9.4
      - requests-oauthlib==2.0.0
      - sacrebleu==2.4.2
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - simplejson==3.19.2
      - six==1.16.0
      - sortedcontainers==2.4.0
      - soundfile==0.12.1
      - soxr==0.3.7
      - tabulate==0.9.0
      - threadpoolctl==3.5.0
      - timm==1.0.7
      - tomli==2.0.1
      - tornado==6.4.1
      - ultralytics==8.2.48
      - ultralytics-thop==2.0.0
      - unicodedata2==15.1.0
      - urllib3==1.26.19
      - xlsxwriter==3.2.0
      - xxhash==3.4.1
      - yapf==0.40.2
      - yarl==1.9.4
      - zhconv==1.4.3
      - zipp==3.19.2
      - transformers==4.42.3
